---
title: "Reproducible Reporting_Assignment 5"
author: "Ashlyn Bray"
date: "2024-10-03"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
leadIQ <- read.csv("../DataRaw/lead-iq-01.csv")
```

## R Markdown

```{r plot}
ggplot(leadIQ, aes(x = Smelter, y = IQ, fill = Smelter)) +
  geom_boxplot() +
  labs(title = "IQ Levels by Location Status",
       x = "Location Status",
       y = "IQ Level") +
  theme_minimal() +
  theme(legend.position = "none")
```

## Descriptive Tables

```{r pressure, echo=FALSE}
summary_table <- data.frame(
  Location = c("Far", "Near"),
  Mean_IQ = c(mean(leadIQ$IQ[leadIQ$Smelter == "Far"]), 
              mean(leadIQ$IQ[leadIQ$Smelter == "Near"])),
  SD_IQ = c(sd(leadIQ$IQ[leadIQ$Smelter == "Far"]), 
            sd(leadIQ$IQ[leadIQ$Smelter == "Near"])),
  Median_IQ = c(median(leadIQ$IQ[leadIQ$Smelter == "Far"]), 
                median(leadIQ$IQ[leadIQ$Smelter == "Near"])),
  Q1_IQ = c(quantile(leadIQ$IQ[leadIQ$Smelter == "Far"], 0.25, na.rm = TRUE), 
             quantile(leadIQ$IQ[leadIQ$Smelter == "Near"], 0.25, na.rm = TRUE)),
  Q3_IQ = c(quantile(leadIQ$IQ[leadIQ$Smelter == "Far"], 0.75, na.rm = TRUE), 
             quantile(leadIQ$IQ[leadIQ$Smelter == "Near"], 0.75, na.rm = TRUE)))

# Print the table using kable
kable(summary_table, 
      caption = "Summary of IQ Levels by Location Status", 
      digits = 2) %>%
  kable_styling(full_width = FALSE, position = "center")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
